---
- name: "End the play for hosts that do not run CentOS or RHEL"
  meta: end_host
  when:
  - ansible_distribution != 'CentOS' and ansible_distribution != 'RedHat' 

- name: "Check if the CA certificate exist"
  stat:
    path: "{{ ca.dir }}/{{ ca.cert }}"
  register: ca_cert_exists
  ignore_errors: true

- name: "Check if the CA key exist"
  stat:
    path: "{{ ca.dir }}/{{ ca.key }}"
  register: ca_key_exists
  ignore_errors: true

- name: "End the play if the CA certificate does not exists on {{ inventory_hostname }}"
  fail: 
    msg: "CA certificate does not exist"
  when: "not ca_cert_exists.stat.exists"

- name: "End the play if the CA key does not exists on {{ inventory_hostname }}"
  fail: 
    msg: "CA key does not exist"
  when: "not ca_key_exists.stat.exists"

- name: "Install python dependencies"
  block:
  - name: "Install python-pip"
    yum:
      name: python-pip
      state: latest
    become: true
  
  - name: "Install cryptography module"
    pip:
      name: cryptography
      state: latest
    become: true
